server {
    listen 80;
    server_name localhost;

    location /api/status {
        default_type application/json;
        return 200 '{"status":"ok","message":"Dummy Nginx API is running"}';
    }
}